<?php if ($block->isEnabled()): ?>
    <!--// BEGIN Fera.ai Integration Code //-->
    <script>
        window.feraStandaloneMode = true;
        window.fera = window.fera || [];
        <?= $block->getDebugJs(), PHP_EOL; ?>
        window.fera.push('loadPlatformAdapter', "magento2");
        window.fera.push('configure', {
            api_key: "<?= $block->getPublicKey(); ?>",
            app_url: "<?= $block->getAppUrl(); ?>",
            api_url: "<?= $block->getApiUrl(); ?>",
        });
     </script>

    <?= $this->getChildHtml('fera_ai.footer.product.view'); ?>
    <script async type="application/javascript" src="<?= $block->getJsUrl(); ?>"></script>
    <!--// END Fera.ai Integration Code //-->
<?php endif; ?>
